---
- name: 'Add entries to OpenBao server'
  hosts: 'openbao'
  gather_facts: true
  become: false

  tasks:

    - name: 'Write a value'
      community.hashi_vault.vault_kv2_write:
        # authentication and Vault URL
        url: "http://{{ hostvars['openbao']['ansible_default_ipv4']['address'] }}:8200"
        token_file: 'openbao_root_token'
        token_path: "{{ playbook_dir }}"
        auth_method: 'token'
        # actual things to do
        path: 'foo'
        data:
          test: 'vagrant-libvirt'
        read_before_write: true
      delegate_to: 'localhost'
      become: false
